### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by jurgen2005** [DeerMaximum/QR-Code-Generator#109]
Getting "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble" 
upon trying to add the custom component
version 2.1.5

**Comment by DeerMaximum** [comment]
Try the 2.1.4 version. The 2.1.5 requires at least Home Assistant 2024.2.0.

**Comment by jurgen2005** [comment]
thx, just saw the remark, you are early with 24.2 support :-)
