### ISSUE TITLE
Example Configuration

### ISSUE THREAD

**Issue by jlong23** [DeerMaximum/QR-Code-Generator#13]
I know it's an early release, would it be possible to add an example into the ReadMe.md for configuration?
Much Appreciated for those that don't python that much!

**Comment by DeerMaximum** [comment]
What kind of configuration information are you missing to use the integration?

**Comment by jlong23** [comment]
I assume it's a 'Config.yaml'

''' YAML
camera:
  - platform: qr_generator
    name: Guest WiFi
    content: "WIFI:S:Guest;T:WPA/WPA2;P:Passw0rd!;;"
'''
Which is what I expect to establish a 'Camera' entity to be exposed on a Dashboard.

Am I mistaken on it's usage?

**Comment by jlong23** [comment]
Sorry, I was missing the second step after HACS install to add the 'Integration' into the 'Devices'  
New and getting caus

**Comment by DeerMaximum** [comment]
I have adjusted the setup instructions and highlighted that the integration needs to be added in the devices tab. 

If you have more questions, feel free to create a new issue.
