### ISSUE TITLE
After upgrading HAS OS core to latest version 2024.12.0 the integration fails - Requirements for qr_generator not found: ['pillow==10.4.0'].

### ISSUE THREAD

**Issue by soheiladeli** [DeerMaximum/QR-Code-Generator#211]
After upgrading HAS OS core to latest version 2024.12.0 the integration fails

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 11:34:21 AM (3 occurrences)
Last logged: 11:34:26 AM

Setup failed for custom integration 'qr_generator': Requirements for qr_generator not found: ['pillow==10.4.0'].

**Comment by pos-ei-don** [comment]
Same here

**Comment by alanmilinovic** [comment]
Same

**Comment by arnocl** [comment]
same

**Comment by StillClueless** [comment]
same

**Comment by jonastaedcke** [comment]
Please add only one comment that is helpful for the issue. For everything else, the emotions are there under a comment.

**Comment by DeerMaximum** [comment]
The new version of this integration should be online

**Comment by Aleksey-nt** [comment]
After updating sensor data, qr image is not updated.
