### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by shreyasajj** [DeerMaximum/QR-Code-Generator#25]
Unable to install package pillow==9.3.0: ERROR: Cannot install pillow==9.3.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts 

same problem as #24 tries to solve

**Comment by shreyasajj** [comment]
This is with the latest 1.0.2

**Comment by rgliese** [comment]
Me to, same Error

**Comment by DeerMaximum** [comment]
I see the problem, with the upcoming Home Assistant release you should be able to install the integration again. So long you can downgrade the version to 1.0.1. As long as the version comes out I will change the realease to a beta release.

**Comment by joostvkempen** [comment]
> 

this kind of creates a new 'problem' : I've already updated to 1.0.2 and now HACS says there's an update, however it wants to actively downgrade from 1.0.2 to 1.0.1. You marked the new release as 'pre-release' instead of 'beta' ??

**Comment by DeerMaximum** [comment]
You need to turn off the "Show beta versions" switch, then the version will not be shown to you as an update.

![Screenshot](https://user-images.githubusercontent.com/43999966/205677571-7d5ceda9-7098-4fad-91f3-fb5b6ad00b8d.PNG)

**Comment by renslinden** [comment]
HA 2022.12 is out and therefor version 1.0.2 is needed. Can you release it?

**Comment by DeerMaximum** [comment]
The version is released.
