### ISSUE TITLE
V1.0.3 on Install Wizard doesn't load

### ISSUE THREAD

**Issue by MattN-HB** [DeerMaximum/QR-Code-Generator#31]
## Describe the bug
Using recommended install method, HACS repo on v1.0.3. After Home instant reboot and integration added the wizard spins with no success.

Only fix was to use v1.0.2

## Debug log

None

**Comment by juan11perez** [comment]
Same here

**Comment by DeerMaximum** [comment]
Should be fixed with Home Assistant 2023.02.

**Comment by DeerMaximum** [comment]
In Home Assistant 2023.02 the setup works again
