### ISSUE TITLE
Requirements for qr_generator not found: ['pillow==9.5.0']

### ISSUE THREAD

**Issue by Sitruk** [DeerMaximum/QR-Code-Generator#39]
I'm receiving this error after updating Home Assistant.

Setup failed for custom integration qr_generator: Requirements for qr_generator not found: ['pillow==9.5.0'].

Home Assistant 2023.4.5
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest

**Comment by DeerMaximum** [comment]
You have to make sure that you install the version 1.0.4 (Beta) of this integration only when you have HA version 2023.5.0 or greater.
