### ISSUE TITLE
Diacritics

### ISSUE THREAD

**Issue by milandzuris** [DeerMaximum/QR-Code-Generator#46]
## Version of the custom_component
2.0

## Describe the bug
Hi please add diacritics to QR Code Generator
![image](https://github.com/DeerMaximum/QR-Code-Generator/assets/42905545/0dbee2d0-eacd-4348-a7ff-f6d1ad22d3ba)

**Comment by DeerMaximum** [comment]
Unfortunately I cannot influence this, please contact the Home Assistant developers directly.

**Comment by DeerMaximum** [comment]
Since the error was rejected in the Home Assistant repo, what is the sign that you can't paste?
