### ISSUE TITLE
Home Assistant 2023.8.0 Beta

### ISSUE THREAD

**Issue by milandzuris** [DeerMaximum/QR-Code-Generator#50]
Not Loaded
![image](https://github.com/DeerMaximum/QR-Code-Generator/assets/42905545/617b59f2-e37e-49bf-b03f-7d78e4b9dd25)

Logger: homeassistant.setup
Source: setup.py:209
First occurred: 20:52:53 (1 occurrences)
Last logged: 20:52:53

Setup failed for custom integration qr_generator: Requirements for qr_generator not found: ['pillow==9.5.0'].

**Comment by DeerMaximum** [comment]
You have to make sure that you install the version 2.0.1 (Beta) of this integration when you have HA version 2023.8.0 or greater.

**Comment by milandzuris** [comment]
> You have to make sure that you install the version 2.0.1 (Beta) of this integration when you have HA version 2023.8.0 or greater.

Working
