### ISSUE TITLE
Use case as/with tag

### ISSUE THREAD

**Issue by luzik** [DeerMaximum/QR-Code-Generator#6]
Hi, I'm just wondering is this can help me achieve such a scenario:

I have working face recognition using my door camera, and want to unlock the doors with it, but i am aware of false positive, so my idea is to generate one minute valid qr-code and send it to recognized person phone. Then person have to scan it using my door camera.

I believe that generated tag have to be added to home assistant tags, and removed on scan or validity ends
Is qr-code-generator a way to go ?

**Comment by DeerMaximum** [comment]
Instead of using the tags, you could create a text helper which contains the current "access code". You then display this code via template in the QR code. When the QR code is scanned, you simply compare the two values, open the door accordingly and change the code.

Thats the way I would do it

**Comment by luzik** [comment]
Yeah, I followed your way and it is working fine :) Thx for idea and project :)

**Comment by Dodoooh** [comment]
> Yeah, I followed your way and it is working fine :) Thx for idea and project :)

May I ask what you use to read QR codes in Home Assistant?

**Comment by luzik** [comment]
QR Codehome-assistant.ioWiadomość napisana przez Dodoooh ***@***.***> w dniu 25.09.2022, o godz. 03:23:﻿

Yeah, I followed your way and it is working fine :) Thx for idea and project :)

May I ask what you use to read QR codes in Home Assistant?

**Comment by DeerMaximum** [comment]
There is this integration that enables QR-Code recognition from cameras.
https://www.home-assistant.io/integrations/qrcode/
