### ISSUE TITLE
Generating Guest WiFi QR Code

### ISSUE THREAD

**Issue by firestrife23** [DeerMaximum/QR-Code-Generator#9]
It just doesn't work when I enter the content below

`WIFI:T:WPA;S:guest;P:{{ states('input_text.guest_wifi_password')}};H:0`

The error message

```
Logger: homeassistant.components.camera
Source: custom_components/qr_generator/camera.py:120 
Integration: Camera (documentation, issues) 
First occurred: 8:05:39 PM (4 occurrences) 
Last logged: 8:07:16 PM

Error adding entities for domain camera with platform qr_generator
Error while setting up qr_generator platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/qr_generator/camera.py", line 92, in async_added_to_hass
    self._refresh()
  File "/config/custom_components/qr_generator/camera.py", line 120, in _refresh
    code = pyqrcode.create(
  File "/usr/local/lib/python3.10/site-packages/pyqrcode/__init__.py", line 111, in create
    return QRCode(content, error, version, mode, encoding)
  File "/usr/local/lib/python3.10/site-packages/pyqrcode/__init__.py", line 161, in __init__
    self.data = content.encode(self.encoding)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201d' in position 13: ordinal not in range(256)
```

**Comment by eth0up** [comment]
> It just doesn't work when I enter the content below
> 
> `WIFI:T:WPA;S:guest;P:{{ states('input_text.guest_wifi_password')}};H:0`
> 
> The error message
> 
> ```
> Logger: homeassistant.components.camera
> Source: custom_components/qr_generator/camera.py:120 
> Integration: Camera (documentation, issues) 
> First occurred: 8:05:39 PM (4 occurrences) 
> Last logged: 8:07:16 PM
> 
> Error adding entities for domain camera with platform qr_generator
> Error while setting up qr_generator platform for camera
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
>     await self.async_added_to_hass()
>   File "/config/custom_components/qr_generator/camera.py", line 92, in async_added_to_hass
>     self._refresh()
>   File "/config/custom_components/qr_generator/camera.py", line 120, in _refresh
>     code = pyqrcode.create(
>   File "/usr/local/lib/python3.10/site-packages/pyqrcode/__init__.py", line 111, in create
>     return QRCode(content, error, version, mode, encoding)
>   File "/usr/local/lib/python3.10/site-packages/pyqrcode/__init__.py", line 161, in __init__
>     self.data = content.encode(self.encoding)
> UnicodeEncodeError: 'latin-1' codec can't encode character '\u201d' in position 13: ordinal not in range(256)
> ```

I was also looking forward to the possibility of generating a wifi QR code for my guest dashboard. I was able to generate a scannable wifi QR code in this Integration (it uses `pyqrcode` module under the hood) by following the format outlined here: https://gist.github.com/GammaGames/7736c7741879e32b5ad2c8b587216445

In HA, this is my working config:
`WIFI:S:MY_WIFI_SSID;T:WPA/WPA2;P:MY_WIFI_PASSWORD;;`

FYI: in the content string you posted there is an extra space after the opening braces of the templated value which might affect the template integrity.

Hope this info helps you too!

Cheers

**Comment by firestrife23** [comment]
Thank you, it’s working now.

**Comment by Macleykun** [comment]
> I also use my integration to display a wifi access.
> 
> Here is my template: `WIFI:S:WIFINAME;T:WPA;P:{{states('input_text.gast_wlan_password')}};;`
> 
> Hope I could help you

may i ask where i can fill this info in? I can't find a field to put this string in

**Comment by Macleykun** [comment]
Sorry, i found out where to input the data.
However, is it possible to display the QR code in homekit?

**Comment by Macleykun** [comment]
Also, i how would the template be filled in? I don't seem to get the QR code working. Is it supposed to be filled out as:

```
WIFI:S:Wi-Fi network name;T:WPA;P:{{states('input_text.somesecurepass!')}};;
```
I tried with and withoud the input_text. part.

**Comment by DeerMaximum** [comment]
@Macleykun 
I don't own any Apple devices, so I can't help you with that.

**Comment by Macleykun** [comment]
Understandably!
I don’t think it could work, as HomeKit expects some sort of video output:
![A452B9F3-6AEE-4469-AD4E-584674504C82](https://user-images.githubusercontent.com/26381427/192119209-54be8bba-ed9b-437d-9a89-ccc793ddb476.jpeg)
But I do see it in HA and that’s also helpful :) thanks for everything!
