### ISSUE TITLE
Use "homeassistant" key in hacs.json to set minimum version

### ISSUE THREAD

**Issue by mdeweerd** [DeerMaximum/QR-Code-Generator#90]
The latest version is compatible from 2023.11.0 upwards only, but could still be installed inadvertently.

This can be avoided by using the ["homeassistant" key in hacs.json](https://hacs.xyz/docs/publish/start#hacsjson:~:text=The%20minimum%20required%20Home%20Assistant%20version) which defines the minimum version.

I suggest to add this key to the hacs.json file.

## Debug log

```text

Add your logs here.

```

**Comment by DeerMaximum** [comment]
Thanks for the hint, I missed that key.

**Comment by mdeweerd** [comment]
I suggest that you delete the releases that required this version as well but that did not have that key - otherwise HACS will continue to propose them.
